### PR TITLE
New version (1.1) with global plate motion model support

### PR DESCRIPTION
**Pull request by rogerfraser**
The changes in this pull request relate to a new feature that resolves issue #53. Specifically, this includes:
- New reftran option to select whether to use the Australian plate motion model (default) or to determine which plate motion model parameters to apply according to station location, via `--plate-model-option arg`:
   `0: Assume all stations are on the Australian plate (default)`
   `1: Interpolate plate motion model parameters from a defined`
   `set of global tectonic plates. For this option, a global`
   `tectonic plate boundary file and corresponding Euler`
   `plate motion parameters file must be provided.`
- New reftran options to permit user entry of file locations for:
  - Global tectonic plate boundaries (via `--plate-boundary-file arg`), and
  - Euler pole parameters corresponding to the global tectonic plate boundaries (via `--plate-pole-file`).
- Sample plate boundaries and motion model files, added to [sampleData](https://github.com/icsm-au/DynAdjust/tree/master/sampleData) folder:
  - **PB2002_plates.dig**: List of plate boundaries defined by [Peter Bird, 2003](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2001GC000252)
  - **PB2002_poles.dat**: List of Euler pole parameters corresponding to the plates in PB2002_plates.dig.
  - **TEST_ITRF05.SNX**: Test SINEX file in ITRF2005.
- Creation of a reftran log file (`<network-name>.rft`). Depending on verbose level (via `--verbose-level arg`), output can include information about calculated transformation parameters from Euler pole parameters; sequence of steps involved in reference frame transformations; and reduced Helmert parameters and time duration.
- Updated [DynAdjust User's Guide](https://github.com/icsm-au/DynAdjust/blob/master/resources/DynAdjust%20Users%20Guide.pdf) with new documentation on plate motion model functions, usage and how to import data
- Updated the version number to 1.1

### CODE REVIEW

**Comment by ccrook** [comment]
@rogerfraser This looks great.   I haven't read the code in detail but have a question and a comment!

The question is about the types of observations handled in dnareftran.  If I read it correctly it is only applying coordinate transformations to GNSS baseline and coordinate (or coord set) observations.  What is the rationale in not applying to lat/lon and  directions.  I can see that typically the effect on these is within the expected errors of the observations in any case, but even it is small is is a systematic error in observations which possibly could influence some adjustments.  This could be a lot more significant if the same approach is used to account for deformation where local relative coordinate changes can be more significant.

The comment is more general on the approach of using dnareftran to modify the observations.  As I think we might have discussed before there is an alternative approach which I have used in SNAP.  The approach is to convert the station coordinates to the observation reference frame/epoch for each observation as the observation equations are formed.  This is a bit more work, mainly because it is happening at each iteration.  It also assumes that the differentials with respect to the transformed coordinates are the same as those with respect to the original coordinate system (ie dx in coordinate ref system results in the same change dx in the observation reference frame).  This assumption won't invalidate the adjustment (at least not for any realistic transformation) but in extreme cases it could require an extra iteration to converge.  The main advantage of this approach (apart from needing separate functions to transform observations as well as to transform coordinates) is that it is more robust in areas of more intense deformation where shifting the coordinate could result in a significantly different deformation.  This is not commonly the case.  In dyndadjust this would be handled by iterating the dnareftran stage (if that is where deformation is handled).

**Comment by rogerfraser** [comment]
Many thanks @ccrook for your review and comments.  Much appreciated.
Yep, you're right, the current code base only supports transformation of GNSS baseline and point measurements. The reason for this

**Comment by rogerfraser** [comment]
Many thanks @ccrook for your review and comments. Much appreciated.

Yep, you're right, the current code base only supports GNSS baseline and point measurements.  The reason for this primarily relates to not having support for time-tagging non-GNSS measurements in the DNA and DynaML input file formats, but also reflects the incremental progress being made to provide (eventual) full support. Future enhancements will see changes to the file formats to support time-tagging of measurements and accounting for transformation and deformation in terrestrial measurements. As you know, we're interested in accounting for deformation in spirit levelling adjustments.

On the alternative approach, I remember our conversation well and coming to the conclusion that the two approaches would achieve the same outcome. I'm very interested to test this on the circumstances you've described (intense deformation) and revisit the approach as required. Any data you have in this context would be appreciated.

Can I presume you're comfortable with merging the changes?

Thanks again Chris.

**Comment by ccrook** [comment]
@rogerfraser Just been looking a bit more and two more thoughts. 

1) I suspect the boost point in polygon is a simple 2d planar geometry test (rather than using eg spherioidal geometry).  I don't think that this will work with the PB2002_plates.dig file (below).  This needs to be modified to handle wrapping at 180 degrees and also finding point in polygons that include the pole.  This could be done either by modifying the point file to ensure the polygons are not wrapped, and for polar polygons including an extra edge to the pole and back (maybe from the nearest point on the edge to the pole).  Also the routine would need to be modified to try offsetting the point by 360 degrees if it isn't in the polygon.  But maybe I have missed something in the code that handles this?

2) I couldn't see any new files in the test directory.  It might be worth having a small test adjustment with a point on each plate, maybe at different dates, and see if they come to the right place in an adjustment?

Screenshot from 2020-12-12 06-51-22

**Comment by rogerfraser** [comment]
Thanks @ccrook. On your thoughts:
1. boost's point in polygon algorithm ([within](https://www.boost.org/doc/libs/1_75_0/libs/geometry/doc/html/geometry/reference/algorithms/within/within_2.html)) relies on geometries (points, lines, polygons, etc.) defined by a coordinate system. So yes, it performs a simple 2D planar geometry test if the coordinate system is defined in 2 dimensions as `boost::geometry::cs::cartesian`. For this new feature, the coordinate system was defined as `boost::geometry::cs::geographic` (see [dnageometries.hpp](https://github.com/icsm-au/DynAdjust/commit/da82295ce5a68a2fb1a2203620e6b60011c999e6?branch=da82295ce5a68a2fb1a2203620e6b60011c999e6&diff=split#diff-7544b762fcad65b8d3056c163d06ba3355e9b9b5b614d59f36d56ea578e54314), line 87), which seemed to work quite well with PB2002_plates.dig, despite it not plotting properly in GIS.  For reference, see boost's documentation on [Coordinate Systems](https://www.boost.org/doc/libs/1_75_0/libs/geometry/doc/html/geometry/reference/cs.html). Thinking on this some more, this has just been changed to `spherical_equatorial` (see: https://github.com/icsm-au/DynAdjust/pull/79/commits/c10ed5965608117e124e1cd9842206ea4e6a386f) which appears to provide better support for continuous strings crossing +/-180 and +/-0 values. Without changing the format of the data in PB2002_plates.dig, the algorithm works on plates on the poles (e.g. correctly locates the south pole in the AN plate) and plates crossing the +/-180 meridian (e.g. correctly locates E/W hemisphere points in the PA plate).
2. I'll upload some test data soon, such as a thinned set of one of the APREF solutions (e.g. [apr21087.pdf](https://github.com/icsm-au/DynAdjust/files/5688770/apr21087.pdf)).

**Comment by ccrook** [comment]
Thanks for clarifcation @rogerfraser.  I'd missed the setting of the coordinate system (and I'm clearly not familiar enough with boost).  Sounds excellent.

**Pull request merged**
